In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: bleach in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (0.1.33)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.13/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/anaconda3/lib/python3.13/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/anaconda3/lib/python3.13/site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /opt/anaconda3/lib/python3.13/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.13/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/anaconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in /opt/anaconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/anaconda3/lib/python3.13/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (2026.5.20)

In [3]:
import kagglehub
import pandas as pd

path = kagglehub.dataset_download("tfisthis/influencer-marketing-roi-dataset")

# Use an f-string to tell Pandas to look inside the dynamic path folder
df = pd.read_csv(f"{path}/influencer_marketing_roi_dataset.csv")

df.head()

,campaign_id,platform,influencer_category,campaign_type,start_date,engagements,estimated_reach,product_sales,campaign_duration_days,end_date
0,CAMP100000,TikTok,Fitness,Giveaway,2022-01-01 00:00:00,79900,1892,2834,14,2022-01-15 00:00:00
1,CAMP100001,YouTube,Food,Product Launch,2022-01-02 00:00:00,47985,437228,165,13,2022-01-15 00:00:00
2,CAMP100002,TikTok,Travel,Brand Awareness,2022-01-03 00:00:00,13875,982513,2539,5,2022-01-08 00:00:00
3,CAMP100003,YouTube,Food,Brand Awareness,2022-01-04 00:00:00,41200,213400,100,20,2022-01-24 00:00:00
4,CAMP100004,Instagram,Food,Giveaway,2022-01-05 00:00:00,96998,42501,550,28,2022-02-02 00:00:00

In [4]:
import sys
!{sys.executable} -m pip install kagglehub

Requirement already satisfied: kagglehub in /opt/anaconda3/lib/python3.13/site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (0.1.33)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.13/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kagglehub) (2026.5.20)

# Project Problem Statement: Optimizing Brand Campaign ROI Across the Creator Economy

## Context
A multinational consumer brand allocates millions of dollars annually to influencer marketing across multiple platforms (Instagram, YouTube, TikTok). The marketing team needs to move away from vanity metrics (like follower counts) and deeply understand actual consumer conversion behavior across different audience demographics, creator niches, and content formats.

## The Business Pain Points
The brand wants to uncover which precise factors drive consumer decisions, repeat interactions, and direct product sales. Specifically, they want to analyze:
* **Platform Efficiency**: How consumer engagement shifts between channels.
* **Niche Performance**: Which creator domains (e.g., Tech, Fashion, Fitness) yield the highest transaction volume relative to cost.
* **Campaign Mechanics**: The actual performance impact of tactical variations like exclusive promo codes or giveaways.
* **Seasonality**: How purchasing velocity spikes during critical commercial periods.

## Overarching Analytical Question
> **"How can consumer brand managers leverage creator campaign performance metrics to identify high-converting audience segments, optimize multi-platform ad spend, and systematically maximize Return on Ad Spend (ROAS)?"**

In [5]:
df.head()

,campaign_id,platform,influencer_category,campaign_type,start_date,engagements,estimated_reach,product_sales,campaign_duration_days,end_date
0,CAMP100000,TikTok,Fitness,Giveaway,2022-01-01 00:00:00,79900,1892,2834,14,2022-01-15 00:00:00
1,CAMP100001,YouTube,Food,Product Launch,2022-01-02 00:00:00,47985,437228,165,13,2022-01-15 00:00:00
2,CAMP100002,TikTok,Travel,Brand Awareness,2022-01-03 00:00:00,13875,982513,2539,5,2022-01-08 00:00:00
3,CAMP100003,YouTube,Food,Brand Awareness,2022-01-04 00:00:00,41200,213400,100,20,2022-01-24 00:00:00
4,CAMP100004,Instagram,Food,Giveaway,2022-01-05 00:00:00,96998,42501,550,28,2022-02-02 00:00:00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   campaign_id             150000 non-null  object
 1   platform                150000 non-null  object
 2   influencer_category     150000 non-null  object
 3   campaign_type           150000 non-null  object
 4   start_date              150000 non-null  object
 5   engagements             150000 non-null  int64
 6   estimated_reach         150000 non-null  int64
 7   product_sales           150000 non-null  int64
 8   campaign_duration_days  150000 non-null  int64
 9   end_date                150000 non-null  object
dtypes: int64(4), object(6)
memory usage: 11.4+ MB

In [7]:
df.describe( include='all')

,campaign_id,platform,influencer_category,campaign_type,start_date,engagements,estimated_reach,product_sales,campaign_duration_days,end_date
count,150000,150000,150000,150000,150000,150000.000000,150000.000000,150000.000000,150000.000000,150000
unique,150000,4,7,5,150000,NaN,NaN,NaN,NaN,95811
top,CAMP100000,Instagram,Food,Seasonal Sale,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,2144-02-25 00:00:00
freq,1,59819,21659,30215,1,NaN,NaN,NaN,NaN,7
mean,NaN,NaN,NaN,NaN,NaN,50065.296107,500239.634920,2497.730433,14.976127,NaN
std,NaN,NaN,NaN,NaN,NaN,28847.302798,288003.388219,1443.222587,8.358356,NaN
min,NaN,NaN,NaN,NaN,NaN,100.000000,1002.000000,0.000000,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,25060.500000,251439.500000,1248.000000,8.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,50100.500000,500073.500000,2501.000000,15.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,75045.250000,750016.750000,3746.000000,22.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,99999.000000,999992.000000,4999.000000,29.000000,NaN

In [8]:
df.isnull().sum()

campaign_id               0
platform                  0
influencer_category       0
campaign_type             0
start_date                0
engagements               0
estimated_reach           0
product_sales             0
campaign_duration_days    0
end_date                  0
dtype: int64

In [9]:
import numpy as np

#synthetic fault injection to make sure data contains nan values
np.random.seed(42)


mask_sales = np.random.rand(len(df)) < 0.05


df.loc[mask_sales, 'product_sales'] = np.nan


print("--- Verified Data Quality Check (Permanent Nulls Injected) ---")
df.isnull().sum()

--- Verified Data Quality Check (Permanent Nulls Injected) ---

campaign_id                  0
platform                     0
influencer_category          0
campaign_type                0
start_date                   0
engagements                  0
estimated_reach              0
product_sales             7391
campaign_duration_days       0
end_date                     0
dtype: int64

In [10]:
df['product_sales'] = df.groupby('influencer_category')['product_sales'].transform(lambda x: x.fillna(x.median()))

In [11]:
df.isnull().sum()

campaign_id               0
platform                  0
influencer_category       0
campaign_type             0
start_date                0
engagements               0
estimated_reach           0
product_sales             0
campaign_duration_days    0
end_date                  0
dtype: int64

In [12]:
#snake casing( everything in lowercase with n underscore in b/w)
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(' ', '_')

In [13]:
df.columns

Index(['campaign_id', 'platform', 'influencer_category', 'campaign_type',
       'start_date', 'engagements', 'estimated_reach', 'product_sales',
       'campaign_duration_days', 'end_date'],
      dtype='object')

In [14]:
#creating a cloumn influencer tiers
labels= [ 'Micro-influencer', 'Mid-tier', 'Macro-influencer', 'Meg-influencer']
df['influencer_tier']= pd.qcut(df['estimated_reach'], q=4, labels= labels)
df[['estimated_reach', 'influencer_tier']].head(5)

   estimated_reach   influencer_tier
0             1892  Micro-influencer
1           437228          Mid-tier
2           982513    Meg-influencer
3           213400  Micro-influencer
4            42501  Micro-influencer

In [15]:
# map
platform_overhead_mapping = {
    'YouTube': 14,    # Long-form video production takes about 14 days
    'TikTok': 7,      # Short-form video takes about 7 days
    'Instagram': 5,   # Carousel/Image posts take 5 days
    'Twitter': 2      # Text/Thread campaigns take 2 days
}

df['estimated_production_days'] = df['platform'].map(platform_overhead_mapping)


df[['platform', 'estimated_production_days']].head(10)

    platform  estimated_production_days
0     TikTok                          7
1    YouTube                         14
2     TikTok                          7
3    YouTube                         14
4  Instagram                          5
5    Twitter                          2
6     TikTok                          7
7     TikTok                          7
8  Instagram                          5
9    YouTube                         14

In [16]:
# 1. Intentionally create a completely redundant text column for good practice
df['has_engagement_tracking'] = 'Yes'


print(" Column List with Redundant Field Added ")
print(df.columns.tolist())

 Column List with Redundant Field Added
['campaign_id', 'platform', 'influencer_category', 'campaign_type', 'start_date', 'engagements', 'estimated_reach', 'product_sales', 'campaign_duration_days', 'end_date', 'influencer_tier', 'estimated_production_days', 'has_engagement_tracking']

In [17]:
df.drop('has_engagement_tracking', axis=1, inplace=True)

In [18]:
df.columns.tolist()

['campaign_id',
 'platform',
 'influencer_category',
 'campaign_type',
 'start_date',
 'engagements',
 'estimated_reach',
 'product_sales',
 'campaign_duration_days',
 'end_date',
 'influencer_tier',
 'estimated_production_days']

In [19]:
df.head()

,campaign_id,platform,influencer_category,campaign_type,start_date,engagements,estimated_reach,product_sales,campaign_duration_days,end_date,influencer_tier,estimated_production_days
0,CAMP100000,TikTok,Fitness,Giveaway,2022-01-01 00:00:00,79900,1892,2834.0,14,2022-01-15 00:00:00,Micro-influencer,7
1,CAMP100001,YouTube,Food,Product Launch,2022-01-02 00:00:00,47985,437228,165.0,13,2022-01-15 00:00:00,Mid-tier,14
2,CAMP100002,TikTok,Travel,Brand Awareness,2022-01-03 00:00:00,13875,982513,2539.0,5,2022-01-08 00:00:00,Meg-influencer,7
3,CAMP100003,YouTube,Food,Brand Awareness,2022-01-04 00:00:00,41200,213400,100.0,20,2022-01-24 00:00:00,Micro-influencer,14
4,CAMP100004,Instagram,Food,Giveaway,2022-01-05 00:00:00,96998,42501,550.0,28,2022-02-02 00:00:00,Micro-influencer,5

In [22]:
from sqlalchemy import create_engine

username = "root"
password = ""  
database_name = "influencer_db"

engine = create_engine(f"mysql+pymysql://{username}:{password}@localhost:3306/{database_name}")
df.to_sql(name="campaign_data", con=engine, if_exists="replace", index=False)

150000

In [21]:
import sys
!{sys.executable} -m pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [24]:

df.to_csv('cleaned_influencer_marketing_data.csv', index=False)